# Generated by Django 5.0.3 on 2024-04-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medassistant', '0002_administrator_last_login_administrator_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='password_hash',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='password_hash',
        ),
    ]
