# Generated by Django 5.0.3 on 2024-04-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medassistant', '0003_remove_administrator_password_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
