# Generated by Django 5.0.3 on 2024-04-06 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medassistant', '0004_alter_doctor_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
