# Generated by Django 5.0.3 on 2024-04-06 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medassistant', '0006_doctor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
    ]
